### ISSUE TITLE
Access to the store in components

### ISSUE THREAD

**Issue by Mathieu-R** [developit/stockroom#13]
Hey,

Simple question here, how can I access to the store in my components ?

In Unistore I would use connect() but here it seems that I have no access to actions because they run in a separate worker.

Thanks.

**Comment by Kanaye** [comment]
You just import `connect()` from `unistore` and use it on your components.
Just pass a "mapping" to connect instead of your actions. 
Here an example:
https://github.com/developit/stockroom/blob/0c99699ed38c3cf993e4f08d489da9fa774e5e52/demo/src/index.js#L9-L16

**Comment by Mathieu-R** [comment]
Thanks !

Another question, can we use something else than a string for the first argument of connect() (e.g. In case we have a big store, the string could become really long) ?

And, does it work well with preact-router or react-router (with redux we have react-router-redux to solve some problems that could happen between the store and the router) ?

**Comment by Kanaye** [comment]
I haven't used react-redux-router or similar yet, because I like to handle routes seperated from my data state.
So I don't know.

Regarding the first argument of `connect()`:
stockroom doesn 't provide an own `connect()` function but you can use `unistore`s one.
So you can etheir pass a `string` (as an the example), an array of `string`s or a `function` to map states to `connect()`.
For example:
```javascript
@connect( state => ({ foo: state.foo /* .... */ })
class MyComponent { /* .... */ }
```

**Comment by Mathieu-R** [comment]
Thanks !
