### ISSUE TITLE
Event origin check?

### ISSUE THREAD

**Issue by sammkj** [developit/stockroom#15]
I was reading Tavis Ormandy's tweet about Grammarly's chrome extension vulnerability today. It made me think about stockroom since it is using the same `postMessage` interface. Report can be found [here](https://bugs.chromium.org/p/project-zero/issues/detail?id=1527&desc=2#maincol). Other reference that I found useful: [this](https://security.stackexchange.com/questions/20022/how-to-use-postmessage-securely) and [this](https://securingtomorrow.mcafee.com/technical-how-to/security-risks-arise-insecure-implementations-html5-postmessageapi/)

**Comment by Kanaye** [comment]
Please correct me if I'm wrong or if I missed something!
I don't think this is an issue in stockriim because we are only listening on the events on the worker:
https://github.com/developit/stockroom/blob/d9541ab0e656d5af4b60a8b3cfb575a1f7fe2751/src/index.js#L58
and on events within the worker:
https://github.com/developit/stockroom/blob/0c99699ed38c3cf993e4f08d489da9fa774e5e52/src/worker.js#L79

Afaik events received within the worker, can only be emitted by `postMessage` on the worker object and events triggered by the worker object can only be emitted from within the worker.

So as long as this is the case malicious code would need to already have access to either the worker object or the workers context. And in that case we can 't prevent anything by checking origins because the attack would 've been initiated by probably a cross site scripting attack (in other application/page code) or a user inserting malicious code into his dev-tools.

So afaik stockroom is secure because it doesn't handle messages that could be emitted from other origins.

**Comment by sammkj** [comment]
> we are only listening on the events on the worker

You're right! totally forgot about this. I should have thought more about it before posting. Thanks for the explanation!
